#page title
page_title                                : Coffee Mania                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6472343410                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : uk                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

terms_and_condition_link                  :                                           #terms and condition link

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Coffee Mania                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Coffee Mania is your ultimate companion for managing your caffeine intake and optimizing your daily energy levels.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Kyryl Horbushko                                
your_link                                 : https://khorbushko.github.io
your_city                                 : Lviv
email_address                             : khorbushko@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : gzd3
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Free
    description                           : Coffee Mania is available to users as a completely free app with no hidden costs. You can download and use the app without any charges, subscriptions, or in-app purchases. We believe in making caffeine tracking accessible to everyone, and our commitment is to provide a valuable and feature-rich experience at no cost to you
    fontawesome_icon_name                 : check

  - title                                 : Track everywhere
    description                           : Designed for iPhone and Apple watch, app is available for both your iPhone and Apple Watch, providing seamless integration and a unified caffeine tracking experience across your devices.
    fontawesome_icon_name                 : magic
    
  - title                                 : Dark and light mode
    description                           : With our Dark and Light Mode feature, you can seamlessly switch between two visually pleasing themes to match your mood, environment, or time of day.
    fontawesome_icon_name                 : adjust

  - title                                 : Widgets
    description                           : Customize your home screen with widgets. Get a quick snapshot of your daily caffeine intake, allowing you to make real-time decisions about your next cup of coffee.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : HealthKit integration
    description                           : Coffee Mania goes the extra mile to enhance your health and wellness by seamlessly integrating with Apples HealthKit platform. This integration ensures that your caffeine tracking is not only informative but also contributes to your overall health management
    fontawesome_icon_name                 : heart

  - title                                 : Choose your way
    description                           : We understands that everyone has their own unique tracking preferences and needs. The app offers two distinct tracking modes - Daily Mode and Continuous Mode
    fontawesome_icon_name                 : cogs

  - title                                 : Minimalistic
    description                           : Coffee Mania minimizes the steps required to log your caffeine intake while still providing valuable insights. All you need - it's just a few taps
    fontawesome_icon_name                 : adjust

  - title                                 : Privacy
    description                           : No tracker, no hidden data collection. We follow a strict "no data collection" policy, and your personal information is not collected, stored, or shared by the app. Your privacy is of the highest priority
    fontawesome_icon_name                 : user-secret

  - title                                 : No-ads
    description                           : We offers an ad-free experience, ensuring that your caffeine tracking is not interrupted or compromised by intrusive advertisements. We believe in providing a clean and distraction-free environment for our users.
    fontawesome_icon_name                 : ban

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#BEA79A"

link_color                                : "#7E4F35"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#56330E"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
